services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src/
    networks:
      - app_network
    restart: on-failure
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    user: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_log:/postgres_logs
    networks:
      - app_network
    restart: on-failure

volumes:
  postgres_data:
  postgres_log:

networks:
  app_network:
    driver: bridge