services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src/
    networks:
      - app_network
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:17-alpine
#    build:
#      context: .
#      dockerfile: db.Dockerfile
#    user: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_log:/postgres_logs
    networks:
      - app_network
    restart: on-failure

volumes:
  postgres_data:
  postgres_log:

networks:
  app_network:
    driver: bridge