services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src/
    networks:
      - app_network
    depends_on:
      - db
    restart: on-failure
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    command:
      - '-c'
      - 'logging_collector=on'
      - '-c'
      - 'log_directory=logs'
      - '-c'
      - 'log_statement=all'
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: on-failure

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge